### ISSUE TITLE
Basic README

### ISSUE THREAD

**Issue by srid** [lucasvreis/abacateiro#2]
I'd like to try abacateiro out on my own set of `.org` files (which are pretty basic at the moment). Perhaps some basic commands can be added to README?

**Comment by srid** [comment]
Well, I got it working somewhat. Just had to set the path to my org in the demo YAML file (among other things; PR incoming...). :-)

<img width="390" alt="image" src="https://user-images.githubusercontent.com/3998/170789257-1070ea92-62d7-49b1-8055-928079da75d5.png">

**Comment by srid** [comment]
@lucasvreis Is abacateiro meant to work specifically with [org roam2](https://www.orgroam.com/)? Just curious -- I can try out roam if it requires that.

**Comment by GTrunSec** [comment]
I guess that It should work for roamv2. you know, v1 has been abandoned for a long time.

**Comment by lua-vr** [comment]
OK, when I wrote "Preliminar working version" read as "haskell compiled it and basic stuff is finally working!" :-)

So just expanding on the context a bit, I'm a maths student and the project was originally meant as a way to help me write and publish my org-roam math notes and posts. I'm literally learning Haskell as I write it, so please don't expect too much from it! My original motivation for turning it from a personal blog to something more general and user-friendly was a friend who does not program Haskell but got interested in using it (also the reason I made it public in GitHub). 

So I'm writing it slowly, and for now I will leave it without a README. Many things are missing, but I also need to focus more on pure maths since I'm on my final year and I will be applying to master programs soon.

@srid yes, overall it's meant to be used with org-roam v2 specifically, but you can also use it with normal org pages. There are three types of sources you configure in the yaml file: the zettelkasten (org-roam v2), content (normal org pages) and static files. But only the basics are working.

**Comment by GTrunSec** [comment]
Actually, I'm not a haskell expert and can only contribute a trivial work at the moment. If srid is interested in this idea, that would be a considerable boost. For nix support, I have a better idea of providing a framework based on [std](https://github.com/divnix/std).

**Comment by GTrunSec** [comment]
>So I'm writing it slowly, and for now I will leave it without a README. Many things are missing, but I also need to focus more on pure maths since I'm on my final year and I will be applying to master programs soon.

~Since ema has done a relatively well-done job, I wondered whether it is possible to migrate some abacateiro workload to ema to complete the further work. That would help reduce the work process and avoid wasting each other's energy.~

For the mathematics support,  Can ema embed the [katext](https://github.com/KaTeX/KaTeX/issues/219) easily, even shortcodes like hugo?

Actually, I'm not a haskell expert and can only contribute a trivial work at the moment. If @srid is interested in this idea, that would be a considerable boost. For nix support, I have a better idea of providing a framework based on [std](https://github.com/divnix/std)).

**Comment by lua-vr** [comment]
> Since ema has done a relatively well-done job, I wondered whether it is possible to migrate some abacateiro workload to ema to complete the further work. That would help reduce the work process and avoid wasting each other's energy.

I don't get what you mean here, ema is a library for building static site generators used by abacateiro. Why would one "offload" work to it, when it already does what it is supposed to do?

> For the mathematics support, Can ema embed the [katext](https://github.com/KaTeX/KaTeX/issues/219) easily, even shortcodes like hugo?

Again, this is something abacateiro is concerned, not ema. KaTeX already works, it is just a script you can put in your template (the demo template includes it). More complicated LaTeX like Tikz will also work by using the local texlive to render the graphics to SVG. In fact this was "working" before I rewrote the app, but now I need to reimplement it in a way that allows the user to configure things. As for shortcodes, my idea is using lua scripts à la pandoc to allow something similar.

**Comment by srid** [comment]
@lucasvreis That's all understandable; feel no pressure. :-) Open source is all about no-obligation relaxing fun.

I'm trying out org for _outlines_ (I used to use Workflow and Dynalist to do this) more than note-taking (for which I still use Emanote). I'd like to have some sort of dynamic HTML view for them (this project idea is still fuzzy in my mind). I'm trying out abacateiro to see if there are any ideas I can borrow (also to see if this is something I can use). The use of org-parser / Heist is already a good idea that I'll definitely adopt at some point. `HeistSite` is another potential idea that could probably go in `ema-contrib` or something. 

@GTrunSec I'm not familiar with `std` but I've been increasingly using https://github.com/hercules-ci/flake-parts on my projects.

**Comment by GTrunSec** [comment]
> I don't get what you mean here

Sorry, I should have had a good look at the project when I expressed my opinion. Ema is already one of the dependencies of abacateiro.
