### ISSUE TITLE
Add a default.nix

### ISSUE THREAD

**Issue by JonathanReeve** [lucasvreis/abacateiro#5]
It looks like this relies on [a number of local packages](https://github.com/lucasvreis/organon/blob/main/cabal.project#L2-L5) which could instead be pulled in reliably with a nix config.  That would enable anyone testing organon to just run `nix develop` or equivalent, without having to track down all the dependencies individually. 

@srid, do you have an idea about how best to go about this?

**Comment by srid** [comment]
@JonathanReeve See https://github.com/lucasvreis/organon/pull/3 for background discussion. It may be best to maintain Nix support outside of this repo, since @lucasvreis doesn't use Nix.

As for custom dependencies, check out how Emanote does it:
https://github.com/EmaApps/emanote/blob/9deff5c4f890eb84494420b486e9498d1c001359/flake.nix#L43-L53

**Comment by JonathanReeve** [comment]
So [I made some progress with updating the flake.nix from #3](https://github.com/JonathanReeve/organon/blob/main/flake.nix), but I'm stuck at how to get org-exporters pulled in, which is apparently inside [org-mode-hs](https://github.com/lucasvreis/org-mode-hs). Any ideas about how to access a package which is a subdirectory in nix?

**Comment by srid** [comment]
Here's an example: https://github.com/EmaApps/ema-template/blob/76b141a524a98d456715d0ebf9b2fcd36b47fa32/flake.nix#L39-L41

**Comment by lua-vr** [comment]
Hi everyone, thanks for the interest but as I have said in the other issue (#2), the project is not usable yet (that's why there is no readme). In the next two or three months I plan to have more time to spend on it and do some sort of release, so please watch the repository instead if you are interested.

Even though there is little activity in the repository, the code I have locally has more than 15k lines changed since the last commit in github. The reason for that is that I still use organon daily to preview my notes, but due to time constraints the changes being made require more polishing, and I would not classify the app in its current state as usable. There are breaking changes planned and 3 other packages being written in parallel ([ondim](https://github.com/lucasvreis/ondim), [org-hs](https://github.com/lucasvreis/org-mode-hs), [multiwalk](https://github.com/lucasvreis/multiwalk)), so I would rather not have more people using it for now.

**Comment by lua-vr** [comment]
Regarding local packages, it's due to what I said in the comment above: I have been changing many things at once locally. All of them will be pushed to hackage eventually, there is no need to use nix (and cabal does support source repository packages too). So I'm closing this.

**Comment by lua-vr** [comment]
Perhaps the right thing to do would be to set the repo visibility to private, but this would prevent people from watching changes. I'm not sure. I've written a note in the description in attempt to be more clear about it.

**Comment by srid** [comment]
@lucasvreis You can disable 'Issues' from repository settings.

**Comment by lua-vr** [comment]
@srid I have no problem with the interactions, I'm just a bit sorry that you both spent some time trying to set up nix 😅. What I would like is to prevent more people trying to set it up (and failing for the reasons I wrote above).

**Comment by srid** [comment]
@lucasvreis Feel no pressure. I appreciate you publishing these open source projects. There is no obligation to address every user request. You can see a bunch of user requests [here](https://github.com/srid/neuron/issues) and [here](https://github.com/EmaApps/emanote/discussions) that I just let sit around due to lack of time or interest.
